apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: compo2
  # This is an extra long description
  description: This is my compo2
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - petstore
  consumesApis:
    - petstore
