apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  # This is an extra long description
  description: The Petstore is an example API used to show features of the OpenAPI spec. And I have edited it- Aditya.
  annotations:
    jira/project-key: SEM
    backstage.io/techdocs-ref: value
    sonarqube.org/project-key: Aditya Berojya/adityaberojya
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://demo-app-2.atlassian.net/wiki/spaces/MYS/pages/327908/Demo+Document+1
      title: Confluence Doc
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - petstore
    - streetlights
    - hello-world
