apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: The petstore API
  tags:
    - store
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  adityatype: randomapi
  lifecycle: experimental

  definition: https://github.com/adityaberojya/backstage-demo-2/blob/master/packages/catalog-model/examples/apis/petstore-api.yaml
